### PR TITLE
Extract frontend website (into new repo)

### PR DESCRIPTION
**Pull request by shu8**
This is part of #36.

It turns this repo into serving `static.xrpackage.org`, hosting the core XRPackage files, and creates a new repo that serves `xrpackage.org` hosting the front-end of the site.

I have a new local repo that can be the front-end, where I've moved all the files and updated all the links, but I'm not sure where to push that right now! We could possible make a new `xrpackage-web` repo where the front-end will live?

### CODE REVIEW

**Comment by shu8** [comment]
@avaer Would we need to create a new `xrpackage-web` repo for the new frontend of the site?

I also wasn't sure if we need the `assets/w.blend1`, `assets/w.glb`, `assets/webxr.glb`, `assets/webxr.vox` files. I couldn't find any references to them in the code, so if they're being used I guess it would be outside of this repo?

**Comment by shu8** [comment]
I also searched for references of `xrpackage.org/*.js` and it looks like there's about [30 references](https://github.com/search?q=org%3Awebaverse+xrpackage.org&type=Code) across all the different repos in `webaverse`.

Might it be safer to do some sort of 301 redirect on `xrpackage.org/xrpackage.js` => `static.xrpackage.org/xrpackage.js` and `xrpackage.org/xrpackage/*` => `static.xrpackage.org/xrpackage/*`?

**Comment by avaer** [comment]
> I also wasn't sure if we need the assets/w.blend1, assets/w.glb, assets/webxr.glb, assets/webxr.vox files. I couldn't find any references to them in the code, so if they're being used I guess it would be outside of this repo?

I think some of the w cube assets are used in xrpackage default values for captures. But if that's not the case we can remove these.

The .blend files are the source for the corresponding asset and should be kept as long as the corresponding asset is kept.

**Comment by avaer** [comment]
> Might it be safer to also do some sort of 301 redirect on xrpackage.org/xrpackage.js => static.xrpackage.org/xrpackage.js and xrpackage.org/xrpackage/* => static.xrpackage.org/xrpackage/*, because I think there might be some packages outside of the org that reference the files?

If needed we can do this in a Cloudflare Worker.

**Pull request merged**
